# Generated by Django 3.2.8 on 2021-10-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.TextField(max_length=100)),
                ('game', models.TextField(max_length=100)),
                ('score', models.IntegerField()),
            ],
        ),
    ]
