# Generated by Django 3.2.8 on 2021-10-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='country',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='people',
            name='game',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='people',
            name='name',
            field=models.TextField(max_length=50),
        ),
    ]
