# Generated by Django 3.2.8 on 2021-10-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211012_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='country',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='people',
            name='game',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='people',
            name='name',
            field=models.TextField(max_length=20),
        ),
    ]
